export const CREATE_CONTOH = "CREATE_CONTOH";
export const RETRIEVE_CONTOH = "RETRIEVE_CONTOH";
export const UPDATE_CONTOH = "UPDATE_CONTOH";
export const DELETE_CONTOH = "DELETE_CONTOH";
export const DELETE_ALL_CONTOH = "DELETE_ALL_CONTOH";